### ISSUE TITLE
GTK3 Blend modes functionality

### ISSUE THREAD

**Issue by LunaeSomnia** [Aylur/ags#118]
I've been attempting to use multiple backgrounds on a class with no success. It seems like the css parser doesn't allow it even if [GTK3](https://www.w3.org/TR/css-backgrounds-3/#background) does.

Is it a bug, or am I doing something wrong?

```css
window {
    background-color: transparent;
}

.panel {
    margin: 8px;
    margin-bottom: 0px;
    
    background: rgba(255, 255, 255, 0.5) , rgba(255, 255, 255, 1.0);
    background-blend-mode: normal, color-dodge;

    border-radius: 8px;
}

...
```

```
(ags:113547): Gjs-WARNING **: 20:07:38.049: JS ERROR: Gtk.CssProviderError: style.css:7:40Junk at end of value for background
applyCss@resource:///com/github/Aylur/ags/app.js:56:21
_load@resource:///com/github/Aylur/ags/app.js:153:21
async*vfunc_activate@resource:///com/github/Aylur/ags/app.js:82:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

Thanks for everything.
