### ISSUE TITLE
How can I animate certain propery of a widget?

### ISSUE THREAD

**Issue by sahinakkaya** [Aylur/ags#243]
Let's say when I click to a widget, I want to change its opacity **smoothly** from 100 to 0. When I click again, it will **instantly** go back to 100. How can I make this happen?

I thought about css `transition` property but I don't know if would be applicable here because I want 2 different effects. 

I thought about creating a variable that updates its value and bind opacity to that value. But I don't have enough knowledge to implement this. 

Any help is appreciated!

**Comment by Aiz0** [comment]
You can add `transition-duration` to a class that the button has only when enabled.
```css
.selected {
    transition-duration: 2s;
    opacity: 0;
}
```
And then you can toggle that class when the button is pressed.

```js
Widget.Button({
    label:"test",
    onClicked: self => self.toggleClassName('selected', !self.classNames.includes('selected'))
})
```

**Comment by sahinakkaya** [comment]
Thanks, it works but I tried to give a simple example above. My actual usecase is changing `yalign` property of a label. I can't set `yalign` from css :(

```js
const button = Widget.Button({
  child: Widget.Label("test"),
  onClicked: self => self.toggleClassName('selected', !self.classNames.includes('selected'))
})
```

```css
.selected label {
    transition-duration: 2s;
    yalign: 0; /* normally, yalign takes values between 0 and 1. But it doesn't work here :( */
}
```

**Comment by Aiz0** [comment]
You can use margin to make the label move to a different spot.

Using negative values don't seem to expand the size of the button when the label moves.
```css
.selected label {
    transition-duration: 2s;
    margin: -5px 0 0 0;
}
```

**Comment by Aylur** [comment]
unfortunately there is no builtin way to animate properties available only from javascript code
you would need to implement an easeing function yourself
Maybe we should have a `Utils.ease`, that could take a bezier curve, but I am not that good at math to implement it myself

**Comment by sahinakkaya** [comment]
> Using negative values don't seem to expand the size of the button when the label moves.

Yeah, well... As you said this works for only one side. I want to fully animate it from top to bottom. I used `yalign: 1` property on label to make it appear at the bottom and `margin: -100px 0 0 0;` to make it go top but for some reason, it won't animate with the `yalign` option set. If I don't set it initially, it moves from center to top. I will try to implement what Aylur suggested.

**Comment by Aiz0** [comment]
You can also use margin to position it at the bottom as it's default position.
Add `margin: 0 0 -100px 0;` to button label when its off/not selected.
It should then start at the bottom and move up.

I added a class to the button and made it work with this.
```css
.test-button label {
    margin: 0 0 -20px 0;
}

.selected label {
    transition-duration: 2s;
    margin: -20px 0 0px 0;
}
```

If you can implement an ease function to use with the `yalgin` that might be the better solution though.
