### ISSUE TITLE
How to change font used by ags?

### ISSUE THREAD

**Issue by rafaeljacov** [Aylur/ags#426]
I want to change the font used by ags because some icon doesn't render
![image](https://github.com/Aylur/ags/assets/110229646/57f5b663-4852-4654-8387-6b85f5bde2aa)

**Comment by kotontrion** [comment]
you can change the font using css. This will set the font for all widgets:

```css
* {
  font-family: "your font";
}
```
