### ISSUE TITLE
Janky shrink animation

### ISSUE THREAD

**Issue by Flexksx** [Aylur/ags#676]
I am trying to implement a dynamic notch using Astal. 
This is the source code for the widget:

`DynamicNotchApp.tsx` - widget itself
```typescript
import { App, Astal, Gdk, Gtk } from "astal/gtk3";

export default function DynamicNotch(gdkmonitor: Gdk.Monitor) {
    return (
        <window
            className="DynamicNotch"
            gdkmonitor={gdkmonitor}
            anchor={Astal.WindowAnchor.TOP}
            exclusivity={Astal.Exclusivity.IGNORE}
            application={App}
        >
            <button className={"dynamic-notch"}>
                <label>Dynamic notch</label>
            </button>
        </window>
    );
}
```
`DynamicNotch.scss` - style
```scss
.dynamic-notch{
    min-height: 30px;
    min-width: 300px;
    background-color: black;
    color: white;
    padding-left: 10px;
    padding-right: 10px;
    border-bottom-left-radius: 24px;
    border-bottom-right-radius: 24px;
    border-top-left-radius: 0px;
    border-top-right-radius: 0px;
}

.dynamic-notch:hover{
    min-height: 60px;
    min-width: 500px;
    transition: all;
}
```
`app.ts` - main launch point
```typescript
import { App } from "astal/gtk3";
import style from "./style/main.scss";
import DynamicNotch from "./widgets/bar/notch/DynamicNotchApp";
import DynamicNotchStyle from "./widgets/bar/notch/DynamicNotch.scss";

App.start({
    css: DynamicNotchStyle,
    main() {
        App.get_monitors().map(DynamicNotch)
    },
})
```

And when I hover over the notch, the animation is beautiful. When I stop hovering, the animation will look like some broken rectangulars.

https://github.com/user-attachments/assets/05c2a6e2-a9c1-4670-ac5f-bda556e83465
